yutto-dev/yutto

README.md
poetry.lock
pyproject.toml
yutto/__main__.py
yutto/extractor/common.py
yutto/processor/downloader.py
yutto/processor/progressbar.py
yutto/processor/selector.py
yutto/validator.py

在原来的设想中，bilili/yutto 是以视频下载为核心的，所以并没有考虑在不下载视频的情况下如何去处理相关资源（弹幕、字幕、描述文件），因此 yutto 早期忽略了这些请求
但随着时间的推移，已经发现了多次相关提及，如：
- yutto-dev/bilili#109
- #38
- #104
也就是说对于单独下载弹幕、字幕、描述文件的需求还是比较普遍的，因此本 PR 对下载流程进行重构，增加 `--danmaku-only`、`--metadata-only`、`--subtitle-only` 三个选项，专门提供仅下载单一资源的功能。
重构 cli 解析，移除部分命令行参数检查，调整下载流程，即便不下载音视频也会去尝试下载弹幕等资源。
原有选项语义不变，与原来完全兼容
- 命令行参数检查不再会做这几项的冲突性检查了（也许未来可以在 Action 中加入检查，但因为 flatten_args 特性的存在，需要递归多次解析，总归是有些麻烦，暂时不做了）
- 即便不用 `--overwrite` 选项也会覆盖原有的弹幕、字幕、描述文件资源，但这近乎是零成本的，因为数据在解析阶段已经下载了，只增加了写入硬盘的成本
- closes #104
- 解决了 #38
- 移除的检查项解决了 #93 
-  [ ] …

✨ feat: support `--danmaku-only`, `--metadata-only`, `--subtitle-only`

---

README.md
yutto/__main__.py

批量下载时，大会员因为多端登录、大量下载行为而冻结，需要等待30min或主动刷新，此时，下载到的视频是无大会员情况下的清晰度。
也就是 https://github.com/yutto-dev/yutto/issues/133 的`A2`问题。
提供一个`--vip-check` 参数，给定时，会在下载前校验大会员状态，如果异常则直接退出。
ps: 在run()函数中直接return，不知道是否会引起其他异常？
```bash
poetry run yutto 'https://www.bilibili.com/bangumi/play/ep473904' -c 'x' -d 'download'  --with-metadata --vip-check
> WARN  以非大会员身份登录，注意无法下载会员专享剧集喔～
> 番剧  明日酱的水手服
> ERROR  启用了严格校验大会员模式，请检查SESSDATA或大会员状态！
echo $?
> 0
```
-  [ ] :hammer: …

:sparkles: feat: 添加大会员失效时退出

---

tests/test_processor/test_downloader.py
yutto/extractor/_abc.py
yutto/extractor/bangumi.py
yutto/extractor/bangumi_batch.py
yutto/extractor/cheese.py
yutto/extractor/cheese_batch.py
yutto/extractor/collection.py
yutto/extractor/favourites.py
yutto/extractor/series.py
yutto/extractor/ugc_video.py
yutto/extractor/ugc_video_batch.py
yutto/extractor/user_all_favourites.py
yutto/extractor/user_all_ugc_videos.py
yutto/extractor/user_watch_later.py
yutto/processor/downloader.py
yutto/utils/asynclib.py

closes #135
这是一个已知问题，比如用户用 <kbd>Ctrl</kbd> + <kbd>C</kbd> 暂停下载时，也会有这个问题
问题的原因是 yutto 在各种地方创建了 coroutine，但没有 await，最小复现样例如下：
```python
async def foo():
return 1
foo()
```
对于 #135，是正在遍历一个 coroutine 列表，提前终止会导致后面的元素没有 await
如果想解决该问题，只需要在创建后将未 await 的 close 掉即可
```python
async def foo():
return 1
a = foo()
a.close()
```
此时即可消除该 Warning
第一种方案是在提前终止退出时，对后面的所有元素逐个 close，但是 yutto 目前多处使用了 coroutine，这就需要在多处添加相关维护代码，会非常繁琐
另一种方案是不再返回 coroutine，而是包装成一个新类型，该类型会自动在析构时帮助我们来 close，本 PR 选择了该方案。
本 PR 添加了一个新结构 `CoroutineWrapper`，在 `__del__` 时会自动 close 被包装的 coroutine
```python
RetT = TypeVar("RetT")
class CoroutineWrapper(Generic[RetT]):
coro: Coroutine[Any, Any, RetT]
def __init__(self, coro: Coroutine[Any, Any, RetT]):
self.coro = coro
def __await__(self) -> Generator[Any, None, RetT]:
return (yield from …
```

🐛 fix: automatically close coroutine

---

yutto/utils/filter.py

The default values of both `batch_filter_start_time` and `batch_filter_end_time` are invalid for `.timestamp()`, so it fails in batch mode when the values are not set explicitly. See https://bugs.python.org/issue31212 for details.
This was introduced by #146 .

🐛 fix: timestamp conversion failure

---

yutto/utils/filter.py

解决 issue #157 `OSError: [Errno 22] Invalid argument` 问题。
closes #157
改动`yutto/utils/filter.py`
```python
batch_filter_start_time: datetime.datetime = datetime.datetime(1971,1,1)
batch_filter_end_time: datetime.datetime = datetime.datetime.today()
```

🐛 fix: datetime OSError on Windows Python3.11

---

yutto/utils/ffmpeg.py

The ffmpeg anomalously reads exactly one byte from stdin during video and audio stream merging, disrupting the shell script process which relies on stdin and invokes yutto.
在 `yutto/utils/ffmpeg.py` 中合并音视频的逻辑中会调用 ffmpeg，然而 ffmpeg 在合并时会神秘的从 stdin 里读取一个字节，这会导致调用 yutto 的 shell 脚本出问题（我还认真思考了很久我的 shell 是不是生疏了） 。
btw 如果你也遇到类似的问题话，可以在shell里调用yutto处加一个 `</dev/null`，这样直接把 yutto 的 stdin 给重定向了，也能规避问题。
`subprocess.run()` 调用 ffmpeg，把 stdin 重定向到 `/dev/null`。
-  [ ] …

🐛 fix: prevent ffmpeg read bytes from stdin

---

README.md
yutto/__main__.py
yutto/processor/downloader.py
yutto/utils/asynclib.py

fixes #242
添加 `--download-interval` 参数，以秒为单位，在两话之间暂停一段时间，以免短时间下载大量视频导致账号被封

✨ feat: add `--download-interval` option

---

yutto/api/ugc_video.py

resolves #246
原来考虑到区分度，为分 P 每一 P 设置不同的封面，因此多 P 视频仅第一 P 使用封面，其余使用 `first_frame`，因为一个多 P 视频只有一个封面，但每 P 都有自己的 `first_frame`
但 `first_frame` 对于视频自身来说可能并没有精心挑选的封面更美观，因此统一使用封面

✨ feat: always use `picture` instead of `first_frame`

---

packages/biliass/pyproject.toml
packages/biliass/src/biliass/__init__.py
packages/biliass/src/biliass/__main__.py
packages/biliass/src/biliass/biliass.py
pyproject.toml
uv.lock

protobuf 5.28 新增了 runtime version 和生成 code 版本检查，当前生成 code 版本为 5.28.0，但是 protobuf 目前最新是 5.28.1，会产生如下 warning
```
/Users/username/Projects/yutto/.venv/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.28.0 is older than the runtime version 5.28.1 at protobuf/danmaku.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
```
同 https://github.com/protocolbuffers/protobuf/issues/18096
暂时 filter 掉
-  [ ] :white_check_mark: …

🚨 chore: filter protobuf 5.28 runtime check warning

---

packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/comment.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/writer.rs
packages/biliass/rust/src/writer/mod.rs
packages/biliass/rust/src/writer/rows.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #314
- #315
- #316
- #317
- #318
- (current PR) #319
本 PR 带来部分性能提升（72s -> 60s）
重写后的函数很快，而且是调用次数最多的函数，只需要 500ns 左右（可能更快），理应拿到较大的性能收益，但包装为 pybind 函数后，则到了 5000ns 量级，和纯 python 实现差不多，因此还需要外部调度的 for 循环下沉后才会显现真正的性能收益
-  [ ] :bookmark: …

♻️ refactor: rustify writer utility `test_free_rows`

---

.github/workflows/lint-and-fmt.yml
.vscode/settings.json
packages/biliass/Cargo.toml
packages/biliass/rust/Cargo.lock

fixes #335
maturin build 之后会将 `members` 字段删掉（也许是 cargo 干的），会导致从 sdist 的 PEP 517 build 挂掉
移除该 `Cargo.toml`，更改 VSCode 指向即可获得完善的开发体验

🐛 fix: remove `Cargo.toml` to avoid PEP 517 build error

---

packages/biliass/src/biliass/biliass.py
src/yutto/utils/danmaku.py

#291 step 2
切换到默认 protobuf 弹幕源后，一些热门视频、番剧很容易会弹幕过于密集无法观看，因此默认打开 `reduce_comments`，避免满屏后仍然排新的弹幕
另外 `is_reduce_comments` 参数修改为 `reduce_comments`，为 API 层面的不兼容变动

✨ feat!(biliass): rename `is_reduce_comments` to `reduce_comments` and change it's default value to `True`

---

.github/workflows/biliass-build-and-release.yml
.github/workflows/unit-test.yml

暂时将 ubuntu-latest 降级到 22.04，目前有两处因为 ubuntu-latest 升级到 24.04 挂掉
1. codspeed 明确尚未支持 24.04，见 CodSpeedHQ/runner#42
```
______            __ _____                         __
/ ____/____   ____/ // ___/ ____   ___   ___   ____/ /
/ /    / __ \ / __  / \__ \ / __ \ / _ \ / _ \ / __  /
/ /___ / /_/ // /_/ / ___/ // /_/ //  __//  __// /_/ /
\____/ \____/ \__,_/ /____// .___/ \___/ \___/ \__,_/
https://codspeed.io/     /_/          runner v3.0.0
Error: Error: Only Ubuntu 20.04 and 22.04 are supported at the moment
Error: Process completed with exit code 1.
```
2. maturin sdist build 会挂掉，见 PyO3/maturin-action#291
```
Installing 'maturin' from tag 'v1.7.4'
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/60704b39-958a-466b-96dd-076018ffce2a -f …
```

💚 ci: pin ubuntu to 22.04

---

packages/biliass/rust/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/lib.rs

升级 PyO3 到 0.23 并尝试支持 free-threading
free-threading 不支持 `abi3` feature，需要移除（本 PR 未修改，但本地验证过），但这会对编译流水线有影响（要发好多包），还得看看有没有什么比较好的解决方案

⬆️ deps: bump pyo3 to 0.23 and add free-threading test

---

src/yutto/api/ugc_video.py

一些视频设置成「当前稿件up主设置为仅自见」时，会因为没处理该code而报错
```bash
...
File "/yutto/src/yutto/api/ugc_video.py", line 92, in get_ugc_video_info
assert res_json_data is not None, "响应数据无 data 域"
AssertionError: 响应数据无 data 域
```
增加识别 `code=62012`

🐛 fix: 识别「当前稿件up主设置为仅自见」情形

---

src/yutto/__main__.py

try to fix #423 
问题原因是line.split()直接按照空格split了：
```python
INFO  解析下载列表 test.list 中...
line https://www.bilibili.com/bangumi/play/ss38221/ --batch -p 1~-1 -tp "TV A (2020)/Season 1/E{id}_{name}"
['https://www.bilibili.com/bangumi/play/ss38221/', '--batch', '-p', '1~-1', '-tp', '"TV', 'A', '(2020)/Season', '1/E{id}_{name}"']
```
应该使用`shlex.split`
-  [ ] :question: …

🐛 fix: 修复任务列表中参数值带有空格引起的切分异常

---

src/yutto/__main__.py
src/yutto/_typing.py
src/yutto/extractor/common.py
src/yutto/processor/downloader.py

fixes #457
使 tmp dir 和 out dir 使用相同的结构，之前的话，假如子路径为 `aaa/bbb/ccc`，则两者分别为
- `out/aaa/bbb/ccc`
- `tmp/ccc` <- tmp 下有更高的冲突概率
#281 我们根据 filename 处理了 unique name，tmp 下能够做到唯一，但是会导致 out 多一些没必要的 rename（如 #457 所述）
因此本 PR 后两者将保持相同的目录结构
- `out/aaa/bbb/ccc`
- `tmp/aaa/bbb/ccc`

🐛 fix!: make tmp dir has same hierarchy with output dir

---

.github/workflows/biliass-build-and-release.yml

The changes in the fork were upstreamed and released in 5.5.0. See https://github.com/actions/setup-python/releases/tag/v5.5.0.

👷 ci: replace quansight-labs/setup-python with actions/setup-python

---

docs/.npmrc
scripts/get-version.py

`gbk`  cannt work but default use in windows:
```shell
D:\tmp\yutto>just docs-setup
Traceback (most recent call last):
File "D:\tmp\yutto\scripts\get-version.py", line 42, in <module>
main()
~~~~^^
File "D:\tmp\yutto\scripts\get-version.py", line 31, in main
code = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 10: illegal multibyte sequence
error: Backtick failed with exit code 1
——▶ justfile:3:12
│
3 │ VERSION := `uv run scripts/get-version.py src/yutto/__version__.py`
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
-  [ ] :hammer: …

🐛  fix:  explicit use `utf-8` encoding when read version file

---

packages/biliass/rust/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/reader/xml.rs

升级 quick-xml，根据其修改需要手动处理 unescape（https://github.com/tafia/quick-xml/releases/tag/v0.38.0 、tafia/quick-xml#766）

👽️ deps: bump `quick-xml` to `0.38.0` and unescape manually

---

src/yutto/api/bangumi.py
src/yutto/api/cheese.py
src/yutto/api/ugc_video.py

修复 cheese 字幕获取时的错误
**测试用例**
当发生错误时，输出以下追踪的结果为
```
DEBUG subtitles_info = {'allow_submit': False, 'lan': '', 'lan_doc': '', 'subtitles': [{'id': 1134851933073485824, 'lan': 'ai-zh', 'lan_doc': '中文（自动生成）', 'is_lock': False, 'subtitle_url': '', 'type': 1, 'id_str': '1134851933073485824', 'ai_type': 0, 'ai_status': 2}]}
DEBUG sub_info = {'id': 1134851933073485824, 'lan': 'ai-zh', 'lan_doc': '中文（自动生成）', 'is_lock': False, 'subtitle_url': '', 'type': 1, 'id_str': '1134851933073485824', 'ai_type': 0, 'ai_status': 2}
DEBUG subtitle_url = ''
DEBUG full_url = 'https:'
```
其中ai_status为2怀疑是字幕生成出错
当获取 B站课程（cheese）字幕时，如果 API 返回的 `subtitle_url` 字段为空字符串，程序会构造无效的 URL `"https:"`，导致抛出 `ValueError: unknown url type: '/'` 异常并崩溃。
**错误堆栈**
```
ValueError: unknown url type: '/'
at get_cheese_subtitles() line 132 …
```

🐛 fix: 视频字幕下载中跳过无效的字幕url，避免fetch报错打断下载

---

packages/biliass/rust/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/convert.rs
packages/biliass/rust/src/filter.rs
packages/biliass/rust/src/reader/utils.rs
packages/biliass/rust/src/reader/xml.rs
packages/biliass/rust/src/writer/utils.rs

利用 copilot 优化 biliass 性能
交给 @copilot

⚡️ perf(biliass): improve biliass performance

---

src/yutto/api/ugc_video.py

fixes #559
#274 接口写的有问题，应该是 `aid=xxx` 而非 `avid=xxx`

🐛 fix: fix chapter info API in UGC video when use aid

---

.github/workflows/lint-and-fmt.yml
.github/workflows/vitepress-deploy.yml

-  [x] :construction_worker: ci: 更改 CI 配置文件和脚本

👷 ci: unpin nodejs version
