.github/workflows/api-and-downloader-test.yml
.github/workflows/e2e-test.yml
.github/workflows/latest-release-test.yml
pyproject.toml

-  [ ] :art: style: 对代码语义无影响的格式修改（如去除无用空格、格式化等等修改）

✅ tests: add python3.10 test

---

README.md
yutto/api/acg_video.py
yutto/api/info.py
yutto/cli/batch_get.py
yutto/processor/path_resolver.py

增加子路径模板可选参数：视频上传时间/pubdate
-  [ ] :art: style: 对代码语义无影响的格式修改（如去除无用空格、格式化等等修改）

:sparkles: feat: add subpath parameter pubdate

---

Dockerfile
README.md
justfile

添加一个轻量的 Dockerfile（200MB 左右）
related to https://github.com/SigureMo/yutto/discussions/43
-  [ ] :art: style: 对代码语义无影响的格式修改（如去除无用空格、格式化等等修改）
-  [x] :question: chore: 其它不涉及源码以及测试的修改

🔨 chore: add dockerfile

---

tests/test_downloader.py
yutto/api/acg_video.py
yutto/cli/batch_get.py
yutto/cli/checker.py
yutto/cli/get.py
yutto/processor/downloader.py
yutto/processor/filter.py
yutto/utils/asynclib.py
yutto/utils/fetcher.py
yutto/utils/functools/__init__.py
yutto/utils/functools/filter_none_value.py
yutto/utils/functools/xmerge.py

closes #49 
-  [ ] :art: style: 对代码语义无影响的格式修改（如去除无用空格、格式化等等修改）

⚡️ perf: parallelising video url parser

---

poetry.lock
pyproject.toml
yutto/utils/console/colorful.py

✨ feat: support colorful display on Windows

---

tests/test_api/test_acg_video.py
tests/test_api/test_bangumi.py
yutto/api/acg_video.py
yutto/api/bangumi.py
yutto/api/danmaku.py
yutto/api/info.py
yutto/api/space.py
yutto/extractor/_abc.py
yutto/extractor/acg_video.py
yutto/extractor/acg_video_batch.py
yutto/extractor/bangumi.py
yutto/extractor/bangumi_batch.py
yutto/extractor/common.py
yutto/extractor/favourites.py
yutto/extractor/favourites_all.py
yutto/extractor/series.py
yutto/extractor/uploader_all_videos.py
yutto/utils/fetcher.py
yutto/utils/time.py

related to #59 
-  [x] :label: types: 类型声明修改
-  [x] :construction: wip: 工作正在进行中

🐛 fix: repeated requests

---

yutto/utils/subtitle.py

B站上传SRT字幕时间轴不支持两位毫秒数，所以按理来说应该B站来修，但明显我们来改更方便（不是
时间轴毫秒数固定为3位

🐛 fix: update srt time format

---

tests/conftest.py
tests/test_processor/test_downloader.py
yutto/__main__.py
yutto/extractor/common.py
yutto/processor/downloader.py
yutto/utils/danmaku.py
yutto/utils/file_buffer.py
yutto/utils/metadata.py
yutto/utils/subtitle.py

♻️ refactor: use pathlib instead of os.path

---

.github/workflows/e2e-test.yml
.github/workflows/lint-and-fmt.yml
.github/workflows/unit-test.yml
pyproject.toml

⬆️ deps: bump poetry to 1.2.0

---

.github/workflows/e2e-test.yml
.github/workflows/latest-release-test.yml
.github/workflows/lint-and-fmt.yml
.github/workflows/unit-test.yml
poetry.lock
pyproject.toml

增加 Python3.11 支持
~~看样子还有依赖（aiohttp）不支持 3.11，待支持后再说~~
aiohttp 刚刚发布了 https://github.com/aio-libs/aiohttp/releases/tag/v3.8.3 ，已支持 Python3.11

⬆️ build: add python3.11 support

---

yutto/__main__.py

🐛 fix: `Path(url)` not working on Windows

---

README.md
yutto/__main__.py
yutto/api/space.py
yutto/exceptions.py
yutto/extractor/__init__.py
yutto/extractor/user_watch_later.py

需要经常把稍后再看的视频离线放到NAS
添加一个新批量类型，在给定有效`SESSDATA`和url为`https://www.bilibili.com/watchlater`时，批量下载稍后再看
```
> poetry run yutto -b 'https://www.bilibili.com/watchlater' -c 'xx' -d '/Volumes/Video/B站' --with-metadata -tp='{owner_uid}/{name}'  --vip-strict
> 大会员  成功以大会员身份登录～
>  稍后再看  当前用户
> [1/52]  ~
...
```
当SESSDATA无效时
```
> WARN  以非大会员身份登录，注意无法下载会员专享剧集喔～
> 稍后再看  当前用户
> ERROR  账号未登录，无法获取稍后再看列表哦~ Ծ‸Ծ
```
-  [ ] …

✨ feat: 支持稍后再看视频下载

---

yutto/api/space.py
yutto/api/user_info.py
yutto/utils/fetcher.py

见 #138 
fixes #138
JS 里代码里已经说明了一切，稍微修改下变量名，就可以很清晰地看出算法了，如下代码可通过 Node.js 运行，之后只需要翻译成 Python 代码即可
```js
const crypto = require("crypto");
md5 = (input) => crypto.createHash("md5").update(input).digest("hex");
const time_stamp_1000 = 1685026862432; // Date.now()
function getMixinKey(input_str) {
var t = [];
return (
[
46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5,
49, 33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13, 37, 48, 7, 16, 24, 55,
40, 61, 26, 17, 0, 1, 60, 51, 30, 4, 22, 25, 54, 21, 56, 59, 6, 63, 57,
62, 11, 36, 20, 34, 44, 52,
].forEach(function (num) {
input_str.charAt(num) && t.push(input_str.charAt(num));
}),
t.join("").slice(0, 32)
);
}
function getLocal(e) {
try {
return localStorage.getItem(e);
} catch (t) {
return null;
}
}
function encWbi(params, …
```

👽️ fix: add wbi encode algorithm for wbi apis

---

yutto/api/ugc_video.py

🐛 fix: fix the error when downloading Hi-Res resources for non-vip user

---

README.md
tests/test_api/test_user_info.py
yutto/__main__.py
yutto/_typing.py
yutto/api/user_info.py
yutto/validator.py

1. 有时候大家需要校验登录态而不是大会员 #176 
2. `-strict`参数实际是用户期望识别的异常，因此如果因`-strict`退出应该返回非0
1. 类似`vip-strict`，增加`login-strict`校验登录态
2. 把用户状态的函数合并掉以减少请求，它们请求的同一API
3. `strict`校验失败使用`sys.exit`而不是`return`
-  [x] :label: types: 类型声明修改

✨feat: 增加严格校验登录状态的login-strict

---

Dockerfile
poetry.lock
pyproject.toml
tests/test_api/test_space.py
yutto/__version__.py
yutto/api/space.py

#148 后续，等了一个多月，aiohttp 3.9 正式版终于发了……
-  [x] :bookmark: release: 发布新版本

🔖 release: v2.0.0-beta.31, Python 3.12 support

---

README.md

Add description about Kubespider #200

:pencil: docs: add description about Kubespider to README

---

yutto/processor/downloader.py

fixes #209
当输出路径以 `-` 开头时，FFmpeg 会将输出路径认为是一个 option，因此尝试解析并解析失败，导致无法成功 merge 文件
在输出路径前添加 `--` 解决

🐛 fix: add `--` before output path in ffmpeg command

---

tests/test_api/test_space.py
yutto/api/user_info.py

下载用户视频发生错误，系wbi api鉴权变化，详见[讨论](https://github.com/SocialSisterYi/bilibili-API-collect/issues/868)

🐛 fix: wbi api error

---

tests/test_api/test_space.py
yutto/processor/path_resolver.py
yutto/processor/selector.py

清理一些已经弃用很久的 features
-  [x] :question: chore: 其它不涉及源码以及测试的修改

🔥 chore: remove some deprecated features

---

yutto/api/space.py

支持注销用户的视频下载，如https://space.bilibili.com/360193236
resolves #222
注销后无法通过接口获取用户名称，但是投稿列表的接口可以正常使用
当接口返回-404时，可能存在封号、注销等情况，统一将名称设置为`用户不存在{mid}`。

✨feat: 支持下载注销用户视频

---

yutto/__main__.py
yutto/utils/fetcher.py
yutto/validator.py

encode/httpx#2879 已经弃用 proxies，使用更加明确的 proxy 和 mount
替换 proxies 为 proxy

👽️ refactor: replace `proxies` with `proxy`

---

tests/test_utils/test_data_access.py
yutto/api/bangumi.py
yutto/api/cheese.py
yutto/utils/funcutils/__init__.py
yutto/utils/funcutils/data_access.py

related to #233
为番剧和课程字幕 API 处添加数据 keys 检查，如非预期则报 warning，而不是直接挂掉

🐛 fix: add data check for subtitle

---

yutto/extractor/common.py

resolved #235
仅仅在需要音频或者视频时才尝试获取 playurl
```bash
Before:
❯ poetry run yutto ss38221 -b --danmaku-only   
INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
番剧  关于我转生变成史莱姆这档事 转生史莱姆日记
INFO  全 12 话
INFO  已选择第 1,2,3,4,5,6,7,8,9,10,11,12 话
ERROR  无法获取该视频链接（avid: BV1R64y1y7Qr, cid: 332105623），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1264y1y7n8, cid: 332106369），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1JN411f7A3, cid: 335567223），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1yV411E7BN, cid: 338847790），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1354y1V74m, cid: 342482334），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1xV41177UC, cid: 346014372），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1SB4y1u7v9, cid: 349423199），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV1s54y1G7JP, cid: 353006933），原因：大会员专享限制
ERROR  无法获取该视频链接（avid: BV18X4y1A7WZ, cid: 356530808），原因：大会员专享限制
ERROR …
```

✨ feat: get playurl only required

---

tests/test_api/test_bangumi.py
yutto/api/bangumi.py
yutto/extractor/bangumi.py
yutto/extractor/bangumi_batch.py
yutto/extractor/common.py

使用 v2 playurl API，并清理无用的 `episode_id` 传递（v2 API 不需要这个参数）

👽️ refactor: use playurl v2 API in bangumi

---

yutto/api/bangumi.py
yutto/extractor/common.py

related to #237
B 站目前貌似 `is_preview` 永远是 0，所以只能通过 `badge == "预告"` 这样的方式来判断是否是预告，并不是很可靠

🐛 fix: add missing warning for preview video

---

poetry.lock
pyproject.toml
yutto/_typing.py
yutto/api/bangumi.py
yutto/api/cheese.py
yutto/api/ugc_video.py
yutto/extractor/common.py

https://github.com/yutto-dev/yutto/issues/237#issuecomment-1950709284
添加 `format_ids`，自动根据 id 类型来 format 具体的 id
暂时回退 pyright 到 1.1.349，see https://github.com/microsoft/pyright/issues/7256
-  [x] :question: chore: 其它不涉及源码以及测试的修改

🔊 chore: refine log formatting

---

.gitignore
README.md
justfile
tests/test_utils/test_ffmpeg.py
yutto/__main__.py
yutto/_typing.py
yutto/api/ugc_video.py
yutto/extractor/common.py
yutto/processor/downloader.py
yutto/utils/ffmpeg.py

closes #30, #231
添加封面获取与嵌入到视频的逻辑，目前并不支持为仅音频文件嵌入封面
该行为为默认行为，可通过 `--no-cover` 禁用

✨ feat: support embed cover to video

---

README.md
justfile
yutto/__main__.py

✨ feat: allow use mp3 as audio output format

---

README.md
yutto/__main__.py
yutto/_typing.py
yutto/processor/downloader.py
yutto/utils/fetcher.py

related to https://github.com/yutto-dev/yutto/issues/271#issuecomment-2137902234
允许通过一个新的 option `--banned-mirrors-pattern` 来禁用掉特定的视频/音频 mirror，以免频繁发生 0 速问题

✨ feat: allow ban resource mirror via `--banned-mirrors-pattern` option

---

CONTRIBUTING.md
README.md
_typos.toml
justfile
poetry.lock
pyproject.toml
yutto/__main__.py
yutto/processor/selector.py
yutto/utils/ffmpeg.py
yutto/validator.py

CI 中添加 typos 检查
使用 https://github.com/crate-ci/typos

🔨 ci: fix and integrate typos in CI

---

tests/test_processor/test_path_resolver.py
yutto/__main__.py
yutto/processor/path_resolver.py

fixes #280
在发生同名时，会添加 ` (1)`、` (2)` 后缀，详情见测试 case

🐛 fix: ensure path unique

---

.github/workflows/release.yml
justfile
packages/biliass/src/biliass/__init__.py
packages/biliass/src/biliass/__main__.py
packages/biliass/src/biliass/__version__.py

👷 ci: add release workflow for biliass

---

src/yutto/utils/fetcher.py
tests/conftest.py
tests/test_biliass/test_protobuf.py
tests/test_biliass/test_xml.py

- fixes #296
- same as yutto-dev/bilili#111, #17

🐛 fix: disable ssl verify in httpx client

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml
.gitmodules
justfile
packages/biliass/src/biliass/biliass.py
pyproject.toml
uv.lock

添加 corpus test 确保 biliass 重构过程中不会出问题，因为可能会有大量语料需要存储，因此使用 submodule 以免占用 yutto repo 存储

✅ test: add corpus tests for biliass

---

justfile
packages/biliass/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/comment.rs
packages/biliass/rust/src/error.rs
packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/comment.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/proto.rs
packages/biliass/rust/src/python/reader.rs
packages/biliass/rust/src/reader/mod.rs
packages/biliass/rust/src/reader/xml.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

从前向后逐步重构，目前处于 Reader 部分重构中
rust 重构 XML reader

♻️ refactor: rustify xml reader

---

packages/biliass/rust/src/reader/xml.rs
packages/biliass/src/biliass/biliass.py

♻️ refactor: rustify `filter_bad_chars`

---

packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/writer.rs
packages/biliass/rust/src/writer/ass.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #314
- #315
- #316
- #317
- #318
- #319
- #320
- #321
- #324
- (current PR) #325
本 PR 性能无明显变动

♻️ refactor: rustify ass writer `write_comment`

---

packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/writer.rs
packages/biliass/rust/src/writer/ass.rs
packages/biliass/rust/src/writer/rows.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #314
- #315
- #316
- #317
- #318
- #319
- #320
- #321
- #324
- #325
- (current PR) #326
本 PR 性能大幅提升（27s -> 12s）

♻️ refactor: rustify ass writer `write_normal_comment`

---

packages/biliass/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/error.rs
packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/reader.rs
packages/biliass/rust/src/reader/mod.rs
packages/biliass/rust/src/reader/special.rs
packages/biliass/rust/src/reader/xml.rs
packages/biliass/rust/src/writer/ass.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #314
- #315
- #316
- #317
- #318
- #319
- #320
- #321
- #324
- #325
- #326
- #327
- #328
- (current PR) #329
重新实现的高级弹幕 parser 相比于原来的更加鲁棒，因此 snapshot 里多了一些原本无法解析的结果

♻️ refactor: rustify `parse_special_comment`

---

justfile
packages/biliass/rust/src/comment.rs
packages/biliass/rust/src/convert.rs
packages/biliass/rust/src/lib.rs
packages/biliass/rust/src/python/convert.rs
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/python/writer.rs
packages/biliass/rust/src/reader/protobuf.rs
packages/biliass/rust/src/reader/xml.rs
packages/biliass/src/biliass/_core.pyi
packages/biliass/src/biliass/biliass.py

- #306
- #307
- #308
- #309
- #310
- #311
- #312
- #314
- #315
- #316
- #317
- #318
- #319
- #320
- #321
- #324
- #325
- #326
- #327
- #328
- #329
- #330
- #331
- #332
- (current PR) #336

♻️ refactor: rustify `xml_to_ass` and `protobuf_to_ass`

---

src/yutto/extractor/ugc_video_batch.py

- related to #339
- same as #341

🐛 fix: support festival link for batch download

---

.github/workflows/unit-test.yml
pyproject.toml
uv.lock

集成 codspeed 测试，避免 biliass 性能回归
目前利用 python pytest 测试框架，后续可能会直接使用 rust 测试框架，参考文档 https://docs.codspeed.io/benchmarks/python
-  [x] :technologist: dx: 优化开发体验
-  [x] :construction_worker: ci: 更改 CI 配置文件和脚本

✅ test(biliass): integrate codspeed benchmark test

---

packages/biliass/rust/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/convert.rs

⚡️ perf: use `rayon` to parallel parse process

---

README.md
packages/biliass/README.md
packages/biliass/src/biliass/__main__.py
src/yutto/__main__.py
src/yutto/_typing.py
src/yutto/processor/downloader.py
src/yutto/utils/danmaku.py

resolves #291
#350、#351、#352 的 biliass 重构已经为 #291 提供了充分的支持，本 PR 将相关选项暴露到 cli 并传递给 biliass，以实现相关控制

✨ feat: expose danmaku options

---

.gitignore
README.md
justfile
pyproject.toml
schemas/schema.json
scripts/generate-schema.py
src/yutto/__main__.py
src/yutto/cli/cli.py
src/yutto/cli/settings.py
src/yutto/processor/parser.py
src/yutto/utils/file_buffer.py
src/yutto/validator.py
uv.lock

增加基础的配置文件支持，目前仅支持搜索当前目录 `yutto.toml` 和 `XDG_CONFIG_HOME/yutto/yutto.toml`，尚不支持配置路径自定义

✨ feat: add basic config file support

---

README.md
src/yutto/cli/cli.py
src/yutto/cli/settings.py

#354 仅支持了配置自动发现，并没有支持指定某一路径为配置路径
通过预先解析 `--config`，确保配置的提前加载

✨ feat: support customize config path by `--config`

---

README.md
src/yutto/_typing.py
src/yutto/cli/cli.py
src/yutto/extractor/common.py
src/yutto/processor/downloader.py
src/yutto/processor/parser.py
src/yutto/utils/funcutils/option.py

此前对于配置中的 `~` 是不支持的，在 cli 中 `~` 是天然支持的，但配置中需要额外 expand 一下
另外「小技巧」中不再推荐使用命令 alias 和 alias-file，推荐统一使用配置文件定制

✨ feat: support use `~` in path config and recommend to use config rather than alias file and cli alias

---

.github/workflows/e2e-test.yml
.github/workflows/latest-release-test.yml
.github/workflows/unit-test.yml

3.13 final release 已经发布，尝试删掉 `-dev` 后缀（目前尝试失败）

👷 ci: remove `-dev` specifier for python 3.13

---

src/yutto/processor/downloader.py
src/yutto/utils/asynclib.py

#358 挂在了 `get_size`，本 PR 尝试通过获取 mirrors 的 size 以降低发生的概率
closes #358

✨ feat: use mirrors to get video and audio size to avoid connection error

---

README.md
pyproject.toml
src/yutto/cli/settings.py
uv.lock

➖ deps: remove dependency `xdg` to avoid conflict with `pyxdg`

---

.github/workflows/latest-release-test.yml

避免出现 #335 这种从源码 build 出错的问题
为 biliass 也添加 latest release test

👷 ci(biliass): add latest release test for biliass

---

packages/biliass/rust/Cargo.toml

https://doc.rust-lang.org/cargo/reference/profiles.html

⚡️ perf(biliass): update release profile to optimize performance

---

src/yutto/utils/danmaku.py

调整弹幕默认 `duration_marquee` 和 `duration_still`（约为原来 2x 速），即默认行为尽可能对齐 web 端播放效果，避免弹幕长时间驻留的问题

🔧 chore: optimize default danmaku duration options

---

src/yutto/api/ugc_video.py
src/yutto/validator.py
tests/test_api/test_ugc_video.py

fixes #374 (closes #374)
原来的 API 已经失效，因此必须更新
值得注意的是，新的 API 需要登录，非登录情况下无法获取字幕，目前 CI 也无法测试该 case，目前只能 skip

👽️ fix: update to new subtitle API for UGC video

---

pyproject.toml
uv.lock

ShigureLab/python-lib-starter#61

🔧 chore: use PEP 735 dependency group

---

src/yutto/utils/fetcher.py

fixes #379
相关问题偶尔会出现，虽然我这只有极小概率出现，难以调试
暂时捕获重试，虽然这样并不合适，但为了稳定性暂时也只能这样
也许后续更新 httpx、httpcore 后就没有这个问题了

🐛 fix: catch semaphore error to improve download stability

---

packages/biliass/src/biliass/__init__.py
packages/biliass/src/biliass/biliass.py

💥 feat!: remove deprecated API `Danmaku2ASS`

---

.github/workflows/biliass-build-and-release.yml

CI 添加 free-threading build
Windows 需要拆分成两条不同流水线，否则 3.13t 会覆盖掉 3.13，最终只有一个 wheel 包
-  [x] :construction_worker: ci: 更改 CI 配置文件和脚本

👷 ci(biliass): build free threading version for biliass

---

.gitignore
README.md
justfile
schemas/config.json
src/yutto/cli/cli.py
src/yutto/cli/settings.py
src/yutto/processor/downloader.py
uv.lock

fixes #407
使用 `m4a` 作为默认的音频输出格式，避免音频多一些空白的问题

✨ feat!: change default audio output format to `m4a`

---

pyproject.toml
src/yutto/__main__.py
src/yutto/api/ugc_video.py
uv.lock

⬆️ deps: bump python deps

---

packages/biliass/rust/Cargo.toml
pyproject.toml
src/yutto/api/collection.py
src/yutto/utils/fetcher.py
uv.lock

👽️ fix: update `collections` API

---

.github/workflows/biliass-build-and-release.yml

减少 CI 时间，提升开发效率
仅修改 biliass 源码时才构建全量 wheels
-  [x] :technologist: dx: 优化开发体验

👷 ci(biliass): build all biliass distribution only when modify it source

---

src/yutto/utils/fetcher.py

🐛 fix: catch h2 error to improve download stability

---

README.md
src/yutto/extractor/collection.py
src/yutto/extractor/series.py

Support new collection url
Example: https://space.bilibili.com/1907386132/lists/2279673
Because `?type=season` is not necessary param, so I removed it in regex pattern of collection list
https://github.com/yutto-dev/yutto/issues/431
```python
REGEX_COLLECTION_LIST = re.compile(
r"https?://space\.bilibili\.com/(?P<mid>\d+)/lists/(?P<series_id>\d+)"
)
```
-  [ ] …

✨ feat: support new `lists` entry url for collection and series

---

src/yutto/processor/downloader.py

fixes #446
#109 添加的 vtag 会导致 HDR 视频失效，因此当遇到 HDR 视频时，跳过 vtag

🐛 fix: don't attach vtag for dolby vision

---

src/yutto/api/bangumi.py

https://www.bilibili.com/bangumi/play/ep744327 发现的，番剧（含电影）也是有杜比音频的了，从 ugc 逻辑中 copy 过来，flac 还是没有的，暂不 copy

✨ feat: support download dolby audios for bangumi

---

.github/workflows/biliass-build-and-release.yml
docs/package.json
docs/pnpm-lock.yaml
packages/biliass/rust/Cargo.lock
packages/biliass/rust/Cargo.toml
packages/biliass/rust/src/python/mod.rs
packages/biliass/rust/src/reader/protobuf.rs
packages/biliass/rust/src/reader/xml.rs
pyproject.toml
src/yutto/cli/settings.py
uv.lock

use rust 1.85 and edition 2024
-  [x] :technologist: dx: 优化开发体验

🔧 chore(biliass): use rust 2024 edition

---

src/yutto/extractor/collection.py
src/yutto/extractor/favourites.py
src/yutto/extractor/series.py
src/yutto/extractor/ugc_video_batch.py
src/yutto/extractor/user_all_favourites.py
src/yutto/extractor/user_all_ugc_videos.py
src/yutto/extractor/user_watch_later.py

fixes #462
同 `NotFoundError`，`NoAccessPermissionError` 也应该捕获并跳过

🐛 fix: catch `NoAccessPermissionError` at get info stage

---

docs/guide/supported-links.md
src/yutto/extractor/user_watch_later.py

✨ feat: support parse list page for user watch later

---

src/yutto/processor/downloader.py
src/yutto/validator.py

之前 cover 一直生成在 tmp dir，虽然在不设置 tmp dir 时也没什么问题，但这是错误的实现

🐛 fix: ensure save cover to output dir rather than tmp dir

---

src/yutto/processor/downloader.py

fixes #469
确保所有 `*_data` 只要有数据就会 save，虽然可能会保存后再删除（影响不大），但总比后面再报错好

🐛 fix: ensure all extra data saved before cleanup

---

docs/.vitepress/config.mts
docs/package.json
docs/pnpm-lock.yaml

📝 docs: generate `llm.txt` by using `vitepress-plugin-llms`

---

src/yutto/api/bangumi.py
src/yutto/utils/fetcher.py

https://www.bilibili.com/bangumi/play/ep826152 原有 API 会出现一些奇怪的字幕，每次还随机，实际上这个视频没有字幕

👽️ fix: use new subtitle api in bangumi

---

src/yutto/__main__.py
src/yutto/_typing.py
src/yutto/extractor/_abc.py
src/yutto/extractor/bangumi.py
src/yutto/extractor/bangumi_batch.py
src/yutto/extractor/cheese.py
src/yutto/extractor/cheese_batch.py
src/yutto/extractor/collection.py
src/yutto/extractor/common.py
src/yutto/extractor/favourites.py
src/yutto/extractor/series.py
src/yutto/extractor/ugc_video.py
src/yutto/extractor/ugc_video_batch.py
src/yutto/extractor/user_all_favourites.py
src/yutto/extractor/user_all_ugc_videos.py
src/yutto/extractor/user_watch_later.py

重新组织数据关系，为 cli - extractor - downloader 解耦做准备

♻️ refactor: introduce `ExtractorOptions` for improved argument handling in extractors

---

src/yutto/__main__.py
src/yutto/download_manager.py

拆分下载逻辑（extractor & downloader）到 `download_manager.py`，extrator 和 downloader 还没解耦是因为现在相互之间还有关联性（链接要在下载前一刻真正解析）

♻️ refactor: Split download main logic into `download_manager.py`

---

.vscode/mcp.json
pyproject.toml
src/yutto/__main__.py
src/yutto/cli/cli.py
src/yutto/mcp.py
uv.lock

✨ feat: add very simple MCP support

---

src/yutto/extractor/ugc_video.py
src/yutto/extractor/ugc_video_batch.py

当输入的链接过于复杂时,会匹配不到 `p=?` 而自动设置 `p=1`, 在使用体验上就是有时指定多 p 中的一个 p, 它下载的总是 p1
修复前:
```shell
(yutto) ➜  yutto git:(parse) uv run yutto --skip-download https://www.bilibili.com/video/BV1vZ4y1M7mQ\?vd_source\=d7601f0fc447d708fff71aa75186ea10\&p\=2\&spm_id_from\=333.788.videopod.episodes
INFO  未提供 SESSDATA，无法下载高清视频、字幕等资源哦～
投稿视频  用 bilili 下载 B 站视频
INFO  开始处理视频 用 bilili 下载 B 站视频
LINK  https://www.bilibili.com/video/BV1vZ4y1M7mQ?p=1 # 这里应该是 p2
INFO  共包含以下 2 个视频流：
INFO  * 0 [AVC ] [ 852x480 ] <480P 清晰 > #3
INFO    1 [AVC ] [ 640x360 ] <360P 流畅 > #3
INFO  共包含以下 3 个音频流：
INFO    0 [MP4A] <128kbps >
INFO    1 [MP4A] < 64kbps >
INFO  * 2 [MP4A] <320kbps >
弹幕  存在可下载弹幕
封面  http://i2.hdslb.com/bfs/archive/89528873eb69fca2352238b30b1443b5c03d61d7.jpg
(yutto) ➜  yutto git:(parse) uv run yutto --skip-download …
```

:sparkles: feat: support for UGC video links containing useless query fields

---

.github/workflows/biliass-build-and-release.yml

https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
-  [x] :construction_worker: ci: 更改 CI 配置文件和脚本

👷 ci(biliass): use macos 15
